#!/usr/bin/env bash
# bash that displays numbers from 1 to 20, 4 and bad luck from china, 9 then bad luck from japan, 17 then bad luck from Italy

count=1

while [ $Counter -le 20 ];
                do 
                echo "$Counter"
                case "$Counter" in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17) 
		echo "bad luck from Italy"
		;;
        	esac 
	        let Counter=Counter+1
done 
