#!/usr/bin/env bash
# bash script that displays To infinity and beyond indefinitely with sleep 2 in between each iteration and I am invincible when receiving a sigterm signal
i=0
while [ $i -le 3 ]
do
	trap "echo I am invincible !!!" SIGTERM
        echo "To infinity and beyond"
        sleep 2
done
